// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628151124_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Review chi tiết các dòng smartphone mới nhất",
                            Name = "Đánh giá điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Description = "So sánh, đánh giá laptop văn phòng & gaming",
                            Name = "Đánh giá Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mẹo & thủ thuật dùng thiết bị điện tử hiệu quả",
                            Name = "Hướng dẫn sử dụng"
                        },
                        new
                        {
                            Id = 4,
                            Description = "So sánh các dòng sản phẩm công nghệ",
                            Name = "So sánh sản phẩm"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriesProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Smartphone các hãng",
                            DisplayOrder = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptop văn phòng, gaming",
                            DisplayOrder = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tablet, iPad",
                            DisplayOrder = 3,
                            Name = "Máy tính bảng"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Smartwatch",
                            DisplayOrder = 4,
                            Name = "Đồng hồ thông minh"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tai nghe có dây & không dây",
                            DisplayOrder = 5,
                            Name = "Tai nghe"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sạc, cáp, pin dự phòng...",
                            DisplayOrder = 6,
                            Name = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "<p>iPhone 15 Pro Max mang đến khung Titan nhẹ hơn, chip A17 Pro mạnh mẽ...</p>",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/uploads/iphone15.jpg",
                            Title = "Đánh giá iPhone 15 Pro Max: Nâng cấp đáng giá?"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "<p>MacBook Air M3 cải thiện hiệu năng và thời lượng pin ấn tượng...</p>",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/uploads/macbook-air-m3.jpg",
                            Title = "Đánh giá MacBook Air M3: Laptop mỏng nhẹ tốt nhất"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "<p>Các bước ghép nối Apple Watch với iPhone và cấu hình cơ bản...</p>",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/uploads/applewatch-setup.jpg",
                            Title = "Hướng dẫn thiết lập Apple Watch lần đầu"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Content = "<p>Hai flagship đầu bảng 2024 cạnh tranh ở camera, hiệu năng và pin...</p>",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/uploads/iphone-vs-samsung.jpg",
                            Title = "So sánh iPhone 15 Pro Max và Galaxy S24 Ultra"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Content = "<p>Danh sách những mẫu tai nghe true wireless chất lượng nhất...</p>",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/uploads/top5-tainghe.jpg",
                            Title = "Top 5 tai nghe không dây đáng mua năm 2026"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryProductId = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chip A17 Pro, khung Titan, camera 48MP.",
                            IsHot = true,
                            Name = "iPhone 15 Pro Max 256GB",
                            Price = 29990000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryProductId = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Snapdragon 8 Gen 3, bút S-Pen, màn 6.8 inch.",
                            IsHot = true,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 26990000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            CategoryProductId = 1,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Camera Leica, sạc nhanh 90W.",
                            IsHot = false,
                            Name = "Xiaomi 14",
                            Price = 18990000m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 4,
                            CategoryProductId = 2,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chip Apple M3, pin 18 giờ, siêu mỏng nhẹ.",
                            IsHot = true,
                            Name = "MacBook Air M3 13 inch",
                            Price = 27990000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoryProductId = 2,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel Core Ultra 7, màn InfinityEdge.",
                            IsHot = false,
                            Name = "Dell XPS 13 9340",
                            Price = 32990000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            CategoryProductId = 3,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chip M2, hỗ trợ Apple Pencil Pro.",
                            IsHot = false,
                            Name = "iPad Air M2 11 inch",
                            Price = 16990000m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 7,
                            CategoryProductId = 4,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Đo SpO2, ECG, chip S9.",
                            IsHot = true,
                            Name = "Apple Watch Series 9 GPS",
                            Price = 10990000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryProductId = 5,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chống ồn chủ động, âm thanh không gian.",
                            IsHot = true,
                            Name = "AirPods Pro 2 USB-C",
                            Price = 5990000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 9,
                            CategoryProductId = 6,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sạc nhanh PD 30W, 2 cổng ra.",
                            IsHot = false,
                            Name = "Pin dự phòng Anker 20000mAh",
                            Price = 790000m,
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.HasOne("CMS.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("CMS.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.HasOne("CMS.Data.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.HasOne("CMS.Data.Entities.CategoryProduct", "CategoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("CategoryProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
